Cafecito_Oriental/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, logout_then_login
urlpatterns = [
    re_path(r'admin/', admin.site.urls),
    re_path(r'Productos/', include('apps.Productos.urls')),
    re_path(r'usuario/', include('apps.usuario.urls')),
    re_path(r'accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    re_path(r'logout/', logout_then_login, name='logout')
]

apps/cmp/urls.py
# from django.conf.urls import url, include
from django.urls import include, re_path, path
from apps.cmp.views import  ProductoView, ProductoNew , ProductoEdit, ProductoInactivar, VentasView, VentasEnc, VentasDet, ventas, VentaDetDelete
from .reportes import reporte_ventas, imprimir_venta

urlpatterns = [
    path(r'productos', ProductoView.as_view(), name='producto_list'),
    path(r'productos/new', ProductoNew.as_view(), name='producto_new'),
    path(r'productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path(r'productos/inactivar/<int:id>', ProductoInactivar, name='producto_inactivar'),
    # path(r'^eliminar/(?P<pk>\d+)/$', ProductosDelete.as_view(), name='Productos_eliminar'),
    path(r'ventas/list', reporte_ventas, name="ventas_print_all"),
    path(r'ventas/', VentasView.as_view(), name='ventas_list'),
    path(r'ventas/new', ventas, name='ventas_new'),
    path(r'ventas/edit/<int:venta_id>', ventas, name='ventas_edit'),
    path(r'ventas/<int:venta_id>/delete/<int:pk>', VentaDetDelete.as_view(), name='ventas_del'),
    path(r'ventas/<int:venta_id>/imprimir', imprimir_venta, name='ventas_print_one'),
]

apps/inv/urls.py
from django.urls import include, path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel

urlpatterns = [
    path(r'categorias/', CategoriaView.as_view(), name='categoria_list'),
    path(r'categoria/new', CategoriaNew.as_view(), name='categoria_new'),
    path(r'categoria/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path(r'categoria/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    path(r'subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path(r'subcategoria/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path(r'subcategoria/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path(r'subcategoria/delete/<int:pk>', SubCategoriaDel.as_view(), name='categoria_del'),
]

cafe/urls.py
from django.contrib import admin
from django.urls import include, re_path, path
from django.contrib.auth.views import LoginView, logout_then_login
from apps.venta.views import index
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path('admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^venta/', include('apps.venta.urls')),
    re_path(r'^usuario/', include('apps.usuario.urls')),
    re_path(r'empleados/', include('apps.empleados.urls')),
    re_path(r'cliente/', include('apps.cliente.urls')),
    re_path(r'Productos/', include('apps.Productos.urls')),
    re_path(r'inv/', include(('apps.inv.urls', 'inv'), namespace='inv')),
    re_path(r'cmp/', include(('apps.cmp.urls', 'cmp'), namespace='cmp')),
    re_path(r'^accounts/login/', LoginView.as_view(template_name="usuario/index.html"),name="login"),
    re_path(r'^logout/', logout_then_login, name='logout'),
    re_path(r'reset_password/', auth_views.PasswordResetView.as_view(template_name="auten/password-reset.html"), name='password_reset'),
    re_path(r'reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="auten/password-confirm.html"), name='password_reset_confirm'),
    re_path(r'reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

cafecitox/urls.py
from django.contrib import admin
#from django.urls import path
from django.urls import include, re_path
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from apps.cliente.views import client
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    re_path(r'$', client, name='index'),
    re_path(r'admin/', admin.site.urls),
    re_path(r'cliente/', include('apps.cliente.urls')),
    re_path(r'usuario/', include('apps.usuario.urls')),
    re_path(r'accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    re_path(r'logout/', logout_then_login, name='logout'),

]

apps/Productos/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Productos(models.Model):
    nombre= models.CharField(max_length=50, default='')
    cantidad_productos=models.IntegerField(validators=[MinValueValidator(0)])
    valor=models.IntegerField(validators=[MinValueValidator(0)])
    descripcion=models.CharField(max_length=70)
    estado=models.BooleanField(default=False)

    def __str__(self):
        return '{} {}'.format(self.Cantidad_Productos,self.Cantidad_Productos)

apps/cmp/models.py
from django.db import models
from apps.bases.models import ClassModelo
from django.core.validators import MinValueValidator
# from apps.cmp.models import Producto

# Create your models here.
class Producto(ClassModelo):
    nombre= models.CharField(max_length=50, default='')
    cantidad_productos=models.IntegerField(validators=[MinValueValidator(0)])
    valor=models.IntegerField(validators=[MinValueValidator(0)])
    descripcion=models.CharField(max_length=70)
    estado=models.BooleanField(default=False)

    def __str__(self):
        return '{} {}'.format(self.Cantidad_Productos,self.Cantidad_Productos)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural="Productos"

class VentasEnc(ClassModelo):
    fecha_venta = models.DateField(null=True, blank=True)
    observacion = models.TextField(blank=True, null=True)
    no_factura = models.CharField(max_length=100)
    fecha_factura = models.DateField(null=True, blank=True)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.observacion)

    def save(self):
        self.observacion = self.observacion.upper()
        self.total = self.sub_total - self.descuento
        super(VentasEnc, self).save()

    class Meta:
        verbose_name_plural = "Encabezado Ventas"
        verbose_name = "Encabezado Venta"

class VentasDet(ClassModelo):
    venta = models.ForeignKey(VentasEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    valor_prv = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    costo = models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)
    
    def save(self):
        self.sub_total = float(int(self.cantidad)) * float(self.valor_prv)
        self.total = self.sub_total - float(self.descuento)
        super(VentasDet, self).save()

    class Meta:
        verbose_name_plural = "Detalles Ventas"
        verbose_name = "Detalle Venta"

apps/venta/models.py
from django.db import models
from apps.cliente.models import Cliente
from apps.Productos.models import Productos
from apps.bases.models import ClassModelo

# Create your models here.
from django.db import models


class Venta(models.Model):
    cliente=models.ForeignKey(Cliente, null=False, on_delete=models.CASCADE)
    fecha_ventas=models.DateTimeField(auto_now_add=True)
    valor=models.IntegerField()
    cantidad=models.CharField(max_length=1000)

    def __str__(self):
        return '{} {}'.format(self.nombre,self.apellido)

apps/Productos/forms.py
from django import forms
from apps.Productos.models import Productos


class Productosform(forms.ModelForm):
    class Meta:
        model=Productos

        fields =[
            'nombre',
            'cantidad_productos',
            'valor',
            'descripcion',
            'estado',
        ]
        labels={
            'nombre':'Nombre',
            'cantidad_productos': 'Cantidad de productos',
            'valor': 'Valor del producto',
            'descripcion': 'Descripcion',
            'estado': 'Estado',
        }
        widgets={
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'cantidad_productos': forms.TextInput(attrs={'class': 'form-control'}),
            'valor': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

apps/cmp/forms.py
from django import forms
from apps.cmp.models import Producto, VentasEnc, VentasDet

class ProductoForm(forms.ModelForm):

    class Meta:
        model=Producto

        fields = [
            'nombre',
            'cantidad_productos',
            'valor',
            'descripcion',
            'estado',
        ]

        labels={
            'nombre':'Nombre',
            'cantidad_productos': 'Cantidad de productos',
            'valor': 'Valor del producto',
            'descripcion': 'Descripcion',
            'estado': 'Estado',
        }

        exclude =[
            'um',
            'fm',
            'uc',
            'fc',
        ]

        widgets={
            'descripcion': forms.TextInput,
            # 'estado' : forms.CheckboxSelectMultiple, 
}

    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

        self.fields['estado'] = forms.BooleanField()

class VentasEncForm(forms.ModelForm):
    fecha_venta = forms.DateField(widget=forms.DateInput())
    fecha_factura = forms.DateField(widget=forms.DateInput())

    class Meta:
        model = VentasEnc
        fields = ['producto', 'fecha_venta', 'observacion', 'no_factura', 'fecha_factura', 'sub_total', 'descuento', 'total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

        self.fields['fecha_venta'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

apps/Productos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.Productos.models import Productos
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy


from apps.Productos.forms import Productosform
from apps.Productos.forms import Productos



# Create your views here.
def index(request):
    return render (request, 'venta/index.html')
#     return render(request, 'Productos/Productos_form.html')
# def Productos_views(request):
#     if request.method =='POST':
#         form = Productosform(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('Productos:Productos_list')
#     else:
#         form=Productosform()
#     return render (request, 'Productos/Productos_form.html',{'form':form})

class ProductosCreate(CreateView):
    model=Productos
    form_class=Productosform
    context_object_name='obj'
    template_name='Productos/Productos_form.html'
    success_url=reverse_lazy('Productos_listar')

class ProductosList(ListView):
    model=Productos
    context_object_name='obj'
    template_name='Productos/Productos_list.html'
    paginate_by = 10

class ProductosEdit(UpdateView):
    model=Productos
    form_class=Productosform
    context_object_name='obj'
    template_name='Productos/Productos_form.html'
    success_url=reverse_lazy('Productos_listar')

class ProductosDelete(DeleteView):
    model=Productos
    context_object_name='obj'
    template_name='Productos/Productos_delete.html'
    success_url=reverse_lazy('Productos_listar')

def ProductosInactivar(request, id):
    template_name="Productos/Productos_inactivar.html"
    contexto={}
    prv=Productos.objects.filter(pk=id).first()
    
    if not prv:
        return HttpResponse("Producto no existe" + str(id))
    
    if request.method=='GET':
        contexto={'obj': prv}
    
    if request.method=='POST':
        prv.estado=False
        prv.save()
        contexto={'obj': 'OK'}
        return HttpResponse("Producto Inactivado")

    return render(request, template_name, contexto)

apps/venta/views.py
from django.shortcuts import render
import datetime

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.venta.form import ventaform
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.venta.models import Venta

def index(request):
    return render (request, 'venta/index.html')

class ventacreate(CreateView):
    model= Venta
    form_class= ventaform
    context_object_name='obj'
    template_name='venta/venta_form.html'
    success_url=reverse_lazy('venta_listar')
    
class ventalistar(ListView):
    model=Venta
    context_object_name='obj'
    template_name='venta/venta_listar.html'
    # paginate_by=10

class ventaeditar(UpdateView):
    model=Venta
    form_class= ventaform
    context_object_name='obj'
    template_name='venta/venta_form.html'
    success_url= reverse_lazy('venta_listar')
    
class ventaborrar(DeleteView):
    model=Venta
    context_object_name='obj'
    template_name='venta/venta_borrar.html'
    success_url= reverse_lazy('venta_listar')

def VentaInactivar(request, id):
    template_name="venta/venta_inactivar.html"
    contexto={}
    prv=Venta.objects.filter(pk=id).first()
    
    if not prv:
        return HttpResponse("Venta no existe" + str(id))
    
    if request.method=='GET':
        contexto={'obj': prv}
    
    if request.method=='POST':
        prv.estado=False
        prv.save()
        contexto={'obj': 'OK'}
        return HttpResponse("Venta Inactivado")

    return render(request, template_name, contexto)

templates/cmp/producto_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
					<!--begin::Modal header-->
					<div class="modal-header">
						<!--begin::Modal title-->
						<h2>Crear Producto</h2>
						<!--end::Modal title-->
						<!--begin::Close-->
						<div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
							<!--begin::Svg Icon | path: icons/duotune/arrows/arr061.svg-->
							<span class="svg-icon svg-icon-1">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
									<rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor" />
									<rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</div>
						<!--end::Close-->
					</div> 
					<!--end::Modal header-->
					<!--begin::Modal body-->
					<div class="modal-body py-lg-10 px-lg-10">
						<!--begin::Stepper-->
						<div class="stepper stepper-pills stepper-column d-flex flex-column flex-xl-row flex-row-fluid" id="kt_modal_create_app_stepper">
							<!--begin::Aside-->
							<div class="d-flex justify-content-center justify-content-xl-start flex-row-auto w-100 w-xl-300px">
								<!--begin::Nav-->
								<div class="stepper-nav ps-lg-10">
									<!--begin::Step 1-->
									<div class="stepper-item current" data-kt-stepper-element="nav">
										<!--begin::Line-->
										<div class="stepper-line w-40px"></div>
        {%if obj %}
        <form method='POST' role="form" class="form-inline" action="{% url 'cmp:producto_edit' obj.pk %}"> 
        {%else %} 
        <form method="POST" role="form" class="form-inline" action="{% url 'cmp:producto_new' %}">
        {%endif%} 
            {% csrf_token %}
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                {%if obj%}Editar {% else %}Nuevo {% endif %}Producto
            </div>
            <div class="dropdown-diviser">
            </div>
            <div class="row">
            {{form.as_p}}
            </div>
            <div class="dropdown-diviser">
            </div>
            <br>
            <div class="row">
                <div class="col">
                    <button class="btn btn-danger btn-circle" style="color: white" type="submit">
                        <span class="fa fa-save">
                        </span></button>
                        {% comment %} <a href="{% url 'inv:producto_list' %}" class="btn btn-success">
                            <span class="fa fa-undo">Cancelar</span>
                        </a> {% endcomment %}
                        <button type="button" class="btn btn-success btn-circle" style="color: white" onclick="return cerrar_modal()"><span class="fa fa-undo"></span>
                        </button> 
                </div>
            </div>
    </form>


            </div>
            </div>
            </div>
        </div>
        </div>
        </div>

    </div>
</div>

templates/cmp/ventas.html
{% extends 'base/base.html' %}

{% block content %}
  <form method="post" class="form-inline" id="frmVentas">
    {% csrf_token %}
    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
      {% if encabezado %}Editar {% else %}Nueva {% endif %}Venta
    </div>
    <div class="dropdown-diviser"></div>
    <div class="row">
      <!-- Inicio en Izquierda -->
      <div class="col-6">
        <!-- Inicio encabezado -->
        <div class="form-group row">
          <label for="" class="col-sm-2 col-form-label">Prod. </label>
          <div class="col-sm-10">{{ form_enc.producto }}</div>
        </div>
        <div class="row">
          <div class="col-6">
            <div class="form-group">
              <label for="id_fecha_venta">Fecha Venta</label>
              {{ form_enc.fecha_venta }}
            </div>
            <div class="form-group">
              <label for="id_descripcion">Descripción</label>
              {{ form_enc.observacion }}
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label for="id_no_factura">No. Factura: </label>
              {{ form_enc.no_factura }}
            </div>
            <div class="form-group">
              <label for="id_fecha_factura">Fecha Factura: </label>
              {{ form_enc.fecha_factura }}
            </div>
            <div class="row">
              <div class="col">
                <label for="sub_Total">Sub Total: </label>
              </div>
              <div class="col">{{ form_enc.sub_total }}</div>
            </div>
            <div class="row">
              <div class="col">
                <label for="decuento">Descuento: </label>
              </div>
              <div class="col">{{ form_enc.descuento }}</div>
            </div>
            <div class="row">
              <div class="col">
                <label for="total">Total: </label>
              </div>
              <div class="col">{{ form_enc.total }}</div>
            </div>
          </div>
        </div>
      </div>
      <!-- Iniciar Derecha -->
      <div class="col-6">
        <div class="row">
          <div class="col">
            <table
              id="example"
              class="table table-striped table-hover dt-responsive table-sm nowrap tbl-productos"
              style="width: 100%"
            >
              <thead>
                <th>Id</th>
                <th class="all">Descripción</th>
                <th class="all">Valor</th>
                <th class="all">Acciones</th>
              </thead>
              <tbody>
                {% for item in productos %}
                  <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.valor }}</td>
                    <td>
                      <button type="button" class="btn btn-warning btn-circle" onclick="selectProducto({{ item.id }}, '{{ item.descripcion }}', {{ item.valor }})">
                        <i class="far fa-hand-pointer"></i>
                      </button>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="form-group row">
          <label for="id_id_producto" class="col-sm-3 col-form-label">Producto</label>
          <div class="col-sm-2">
            <input type="text" readonly class="form-control-plaintext" name="id_id_producto" id="id_id_producto" value="" required />
          </div>
          <div class="col-sm-2">
            <input type="text" readonly class="form-control-plaintext" id="id_descripcion_producto" value="" required />
          </div>
        </div>
        <div class="form-group row">
          <label for="id_cantidad_detalle" class="col-sm-2 col-form-label">Cant:</label>
          <div class="col-sm-2">
            <input type="number" class="form-control" name="id_cantidad_detalle" id="id_cantidad_detalle" value="00" required />
          </div>
          <label for="id_valor_detalle" class="col-sm-4 col-form-label">Valor:</label>
          <div class="col-sm-4">
            <input type="number" class="form-control" name="id_valor_detalle" id="id_valor_detalle" readonly required />
          </div>
          <label for="id_descuento_detalle" class="col-sm-3 col-form-label">% Desc:</label>
          <div class="col-sm-3">
            <input type="number" class="form-control" name="id_descuento_detalle" id="id_descuento_detalle" value="00" required />
          </div>
        </div>
        <div class="form-group row">
          <label for="id_sub_total_detalle" class="col-sm-2 col-form-label">S. Total:</label>
          <div class="col-sm-4">
            <input type="text" readonly class="form-control-plaintext" name="id_sub_total_detalle" id="id_sub_total_detalle" value="00" required />
          </div>
          <label for="id_total_detalle" class="col-sm-2 col-form-label">Total:</label>
          <div class="col-sm-3">
            <input type="text" readonly class="form-control-plaintext col-sm-10" name="id_total_detalle" id="id_total_detalle" value="00" required />
          </div>
          <div class="col-sm-3">
            <button type="button" class="btn btn-sm col-sm-2" onclick="clear_detail();">
              <i class="fa fa-minus-circle" aria-hidden="true"></i>
            </button>
          </div>
        </div>
        <!-- Botones -->
        <div class="dropdown-diviser"></div>
        <div class="row">
          <div class="col">
            <button type="submit" class="btn btn-danger">
              <span class="fa fa-save"></span> Guardar
            </button>
            <a href="{% url 'cmp:ventas_list' %}" class="btn btn-success">
              <i class="far fa-hand-point-left"></i> Cancelar
            </a>
          </div>
        </div>
        <!-- Cierre de botones -->
      </div>
      <!-- Cierre derecha -->
    </div>
    <!-- Inicio detalle -->
    <div class="row">
      <div class="col">
        <table class="table table-striped table-hover dt-responsive nowrap" style="width: 100%">
          <thead>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Valor</th>
            <th>Sub Total</th>
            <th>Desc.</th>
            <th>Total</th>
            <th class="all">Acciones</th>
          </thead>
          <tbody>
            {% for item in detalle %}
              <tr>
                <td>{{ item.producto }}</td>
                <td>{{ item.cantidad }}</td>
                <td>{{ item.valor }}</td>
                <td>{{ item.sub_total }}</td>
                <td>{{ item.descuento }}</td>
                <td>{{ item.total }}</td>
                <td>
                  <a class="btn btn-danger btn-circle" onclick="return abrir_modal('{% url 'cmp:ventas_del' encabezado.pk item.id %}')" href="#" role="button"><i class="far fa-trash-alt" style="color:white"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- Fin del detalle -->
  </form>
{% endblock %}

{% block js_page%}
    <script>
        //Llamar al plugin del datatables
      
          //  $(`.table`).DataTable({
            $(document).ready(function() {
                //$('#example').DataTable({
                     $(`.table`).DataTable({
                  "language": {
                   // "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                   "decimal": "",
                   "emptyTable": "No hay información",
                   "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                   "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                   "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                   "infoPostFix": "",
                   "thousands": ",",
                   "lengthMenu": "Mostrar _MENU_ Entradas",
                   "loadingRecords": "Cargando...",
                   "processing": "Procesando...",
                   "search": "Buscar:",
                   "zeroRecords": "Sin resultados encontrados",
                   "paginate": {
                       "first": "Primero",
                       "last": "Ultimo",
                       "next": "Siguiente",
                       "previous": "Anterior"
                   }
                  }
                });

                $(
                    "#id_cantidad_detalle, #id_descuento_detalle"
                  ).change(function () {
                    calcular_detalle();
                  });

              /*Validar envío de detalle*/
              $("#frmVentas").submit(function(e){
                if($('#id_total_detalle').val()==0 || $('#id_id_producto').val()==0){
                  e.preventDefault();
                  $.alert({
                    type:'red',
                    title:'',
                    content: 'No ha agregado productos o esta sin cantidades'
                  })
                }
              });



      
              });


              function selectProducto(id, descripcion, valor) {
                $("#id_cantidad_detalle").val(0);
                $("#id_valor_detalle").val(valor);
                $("#id_descuento_detalle").val(0);
                $("#id_sub_total_detalle").val(0);
                $("#id_total_detalle").val(0);
                $("#id_id_producto").val(+id);
                $("#id_descripcion_producto").val(descripcion);
                $("#id_cantidad_detalle").focus();
                $("#id_cantidad_detalle").select();
            
                $(`.table`).DataTable().search('').draw();
                
              }
              
              function calcular_detalle() {
                var cant, prec, desc, stotal, total;
          
                cant = $("#id_cantidad_detalle").val();
                cant = cant === "" ? 0 : +cant;
                cant = cant < 0 ? 0 : cant;
          
                prec = $("#id_valor_detalle").val();
                prec = prec === "" ? 0 : +prec;
                prec = prec < 0 ? 0 : prec;
          
                desc = $("#id_descuento_detalle").val();
                desc = desc === "" ? 0 : +desc;
                desc = desc < 0 ? 0 : desc;
          
                desc = desc > cant * prec ? 0 : desc;
          
                stotal = cant * prec;
                total = stotal - (stotal*(desc/100));
                //total = stotal - desc;
          
                cant = $("#id_cantidad_detalle").val(cant);
                prec = $("#id_valor_detalle").val(prec);
                desc = $("#id_descuento_detalle").val(desc);
                stotal = $("#id_sub_total_detalle").val(stotal);
                total = $("#id_total_detalle").val(total);
              }
          
              function clear_detail() {
                $("#id_cantidad_detalle").val(0);
                $("#id_valor_detalle").val(0);
                $("#id_descuento_detalle").val(0);
                $("#id_sub_total_detalle").val(0);
                $("#id_total_detalle").val(0);
                $("#id_id_producto").val("");
            
                $("#id_descripcion_producto").val("");
                $(`.table`).DataTable().search("").draw();
                $("#id_proveedor").focus();
              }
            
              $("#id_proveedor").focus();
        
    </script>    
{% endblock %}




{% block scripts_local %}
<script>
  $(function () {
    $("#id_fecha_factura, #id_fecha_venta").datetimepicker({
      format: "Y-m-d",
      timepicker: false,
    });
  });
</script>
{% endblock %}