Cafecito_Oriental/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, logout_then_login
urlpatterns = [
    re_path(r'admin/', admin.site.urls),
    re_path(r'Productos/', include('apps.Productos.urls')),
    re_path(r'usuario/', include('apps.usuario.urls')),
    re_path(r'accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    re_path(r'logout/', logout_then_login, name='logout')
]

apps/inv/urls.py
from django.urls import include, path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel

urlpatterns = [
    path(r'categorias/', CategoriaView.as_view(), name='categoria_list'),
    path(r'categoria/new', CategoriaNew.as_view(), name='categoria_new'),
    path(r'categoria/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path(r'categoria/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    path(r'subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path(r'subcategoria/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path(r'subcategoria/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path(r'subcategoria/delete/<int:pk>', SubCategoriaDel.as_view(), name='categoria_del'),
]

cafe/urls.py
from django.contrib import admin
from django.urls import include, re_path, path
from django.contrib.auth.views import LoginView, logout_then_login
from apps.venta.views import index
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path('admin/', admin.site.urls),
    re_path(r'^$', index, name='index'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^venta/', include('apps.venta.urls')),
    re_path(r'^usuario/', include('apps.usuario.urls')),
    re_path(r'empleados/', include('apps.empleados.urls')),
    re_path(r'cliente/', include('apps.cliente.urls')),
    re_path(r'Productos/', include('apps.Productos.urls')),
    re_path(r'inv/', include(('apps.inv.urls', 'inv'), namespace='inv')),
    re_path(r'cmp/', include(('apps.cmp.urls', 'cmp'), namespace='cmp')),
    re_path(r'^accounts/login/', LoginView.as_view(template_name="usuario/index.html"),name="login"),
    re_path(r'^logout/', logout_then_login, name='logout'),
    re_path(r'reset_password/', auth_views.PasswordResetView.as_view(template_name="auten/password-reset.html"), name='password_reset'),
    re_path(r'reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="auten/password-confirm.html"), name='password_reset_confirm'),
    re_path(r'reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

cafecitox/urls.py
from django.contrib import admin
#from django.urls import path
from django.urls import include, re_path
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from apps.cliente.views import client
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    re_path(r'$', client, name='index'),
    re_path(r'admin/', admin.site.urls),
    re_path(r'cliente/', include('apps.cliente.urls')),
    re_path(r'usuario/', include('apps.usuario.urls')),
    re_path(r'accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    re_path(r'logout/', logout_then_login, name='logout'),

]

apps/cmp/models.py
from django.db import models
from apps.bases.models import ClassModelo
from django.core.validators import MinValueValidator
# from apps.cmp.models import Producto

# Create your models here.
class Producto(ClassModelo):
    nombre= models.CharField(max_length=50, default='')
    cantidad_productos=models.IntegerField(validators=[MinValueValidator(0)])
    valor=models.IntegerField(validators=[MinValueValidator(0)])
    descripcion=models.CharField(max_length=70)
    estado=models.BooleanField(default=False)

    def __str__(self):
        return '{} {}'.format(self.Cantidad_Productos,self.Cantidad_Productos)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural="Productos"

class VentasEnc(ClassModelo):
    fecha_venta = models.DateField(null=True, blank=True)
    observacion = models.TextField(blank=True, null=True)
    no_factura = models.CharField(max_length=100)
    fecha_factura = models.DateField(null=True, blank=True)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.observacion)

    def save(self):
        self.observacion = self.observacion.upper()
        self.total = self.sub_total - self.descuento
        super(VentasEnc, self).save()

    class Meta:
        verbose_name_plural = "Encabezado Ventas"
        verbose_name = "Encabezado Venta"

class VentasDet(ClassModelo):
    venta = models.ForeignKey(VentasEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.BigIntegerField(default=0)
    valor_prv = models.FloatField(default=0)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)
    costo = models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)
    
    def save(self):
        self.sub_total = float(int(self.cantidad)) * float(self.valor_prv)
        self.total = self.sub_total - float(self.descuento)
        super(VentasDet, self).save()

    class Meta:
        verbose_name_plural = "Detalles Ventas"
        verbose_name = "Detalle Venta"

apps/inv/models.py
from django.db import models
from apps.bases.models import ClassModelo

# Create your models here.
class Categoria(ClassModelo):
    descripcion=models.CharField(max_length=100, help_text='Descripcion de la categoria', unique=True)

    def __str__(self):
        return'{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural='Categorias'

class SubCategoria(ClassModelo):
    categoria=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion=models.CharField(max_length=100, help_text='Descripcion de SubCategoria', unique=True)

    def __str__(self):
        return'{}{}'.format(self.categoria.descripcion, self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural='Sub Categorias'
        unique_together=('categoria','descripcion')

class Marca(ClassModelo):
    descripcion=models.CharField(max_length=100, help_text='Descripcion de la marca', unique=True)

    def __str__(self):
        return'{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural='Marcas'

apps/inv/forms.py
from django import forms
from .models import Categoria, SubCategoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria

        fields = [
            'descripcion',
            'estado',
        ]
        labels = {
            'descripcion':'Descripcion',
            'estado':'Estado',
        }
        widgets = {
            'descripcion':forms.TextInput,
            'estado':forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class SubCategoriaForm(forms.ModelForm):
    categoria=forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    
    class Meta:
        model = SubCategoria

        fields = [
            'categoria',
            'descripcion',
            'estado',
        ]
        labels = {
            'descripcion':'Descripcion de Sub Categoria',
            'estado':'Estado',
        }
        widgets = {
            'descripcion':forms.TextInput,
            'estado':forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **Kwargs):
        super().__init__(*args, **Kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['categoria'].empty_label='Seleccione la Categoria'

apps/inv/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Categoria, SubCategoria
from .forms import CategoriaForm, SubCategoriaForm
from django.urls import reverse_lazy

# Create your views here.
class CategoriaView(LoginRequiredMixin, generic.ListView):
    model=Categoria
    template_name='inv/categoria_list.html'
    context_object_name='obj'
    login_url='login'

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=Categoria
    template_name='inv/categoria_form.html'
    context_object_name='obj'
    form_class=CategoriaForm
    success_url=reverse_lazy('inv:categoria_list')
    login_url='login'

    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
    
class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=Categoria
    template_name='inv/categoria_form.html'
    context_object_name='obj'
    form_class=CategoriaForm
    success_url=reverse_lazy('inv:categoria_list')
    login_url='login'

    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=Categoria
    template_name='inv/categoria_del.html'
    context_object_name='obj'
    success_url=reverse_lazy('inv:categoria_list')

class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model=SubCategoria
    template_name='inv/subcategoria_list.html'
    context_object_name='obj'
    login_url='login'

class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=SubCategoria
    template_name='inv/subcategoria_form.html'
    context_object_name='obj'
    form_class=SubCategoriaForm
    success_url=reverse_lazy('inv:subcategoria_list')
    login_url='login'

    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
    
class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=SubCategoria
    template_name='inv/subcategoria_form.html'
    context_object_name='obj'
    form_class=SubCategoriaForm
    success_url=reverse_lazy('inv:subcategoria_list')
    login_url='login'

    def form_valid(self, form):
        form.instance.um=self.request.user.id
        return super().form_valid(form)
    
class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=SubCategoria
    template_name='inv/subcategoria_del.html'
    context_object_name='obj'
    success_url=reverse_lazy('inv:subcategoria_list')

templates/inv/categoria_del.html
{% extends 'base/base.html' %}

{% block content %}
<form method='post' class="form-inline">
    {%  csrf_token %}

    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
        ¿Desea eliminar {{obj.descripcion}}?
    </div>
    <button class="btn btn-danger" typer="submit" class="btn btn-primary";>Si, eliminar</button>
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
</form>

{% endblock %}

{% block js_page %}
{% endblock %}

templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method='post' class="form-inline">
    {% csrf_token %}
    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
        {% if obj %}Editar {% else %}Nueva {% endif %}Categoria</div>
    <div class="dropdown-divisor"></div>
    <div class="row">
        <div class="col-10">
            <div class="input-group">
                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{ obj.descripcion }} {% endif %}">
            </div>
        </div>
        <p></p>
        <p></p>
        <div class="col">
            <div class="form-group">
                <label for="id_estado">Estado</label>
                <input type="checkbox" id="id_estado" name="estado" value="" {% if obj.estado %} checked {% endif %}>
            </div>
        </div>
    </div>
    <p></p>
    <p></p>
    <div class="dropdown-divisor">
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span> Cancelar</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/inv/categoria_list.html
{% extends 'base/base.html' %} 

{% block content %}
<h1>Listado de Categoria</h1>
<p></p>
<div>
    <a class="btn btn-primary" href="{% url 'inv:categoria_new' %}" role="button"><i class="fa fa-plus-square"></i> Nueva</a>
</div>
<p></p>
{% if not obj %}
<div class="alert alert-info">No hay Categoria</div>
{% else %}
<table class='table table-striped table-hover'>
    <thead>
        <tr>
            <td>Id</td>
            <td>Descripcion</td>
            <td>Estado</td>
            <td>F. Creado</td>
            <td>F. Modif</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if obj %} {% for item in obj %}
        <tr>
            <td>{{item.id}}.</td>
            <td>{{item.descripcion}}.</td>
            <td>{{item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>{{item.fc|date:'d/m/y H:i:s'}}</td>
            <td>{{item.fm|date:'d/m/y H:i:s'}}</td>

            <td>
                <a class="btn btn-warning btn-circle" href="{% url 'inv:categoria_edit' item.id %}" role="button"><i class="far fa-edit"></i></a>

                <a class="btn btn-danger btn-circle" href="{% url 'inv:categoria_del' item.id %}" role="button"><i class="far fa-trash-alt"></i></a>
            </td>
        </tr>
        {% endfor %} {% else %}
        <h1>No hay registros de empleados</h1>
        {% endif %}
        <tbody>
</table>
{% endif %}

<br>
<div class="pagination">
    <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Primero</a>
            <a href="?page={{ page_obj.previous_page_number}}">Previo</a>
            {% endif %}
            <span class="current">
                Página {{page_obj.number}} de {{page_obj.paginator.num_pages}}.
            </span> {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number}}">Siguiente</a>
    <a href="?page={{ page_obj.paginator.num_pages}}">Último &raquo;</a> {% endif %}
    </span>
</div>

{% endblock %}

{% block js_page %}
<script>
    //Llamamos al plugin del datatable
    $(document).ready(function(){
        $('.table')DataTable();
    });
</script>
{% endblock %}

templates/inv/subcategoria_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method='post' class="form-inline">
    {% csrf_token %}
    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
        {% if obj %}Editar {% else %}Nueva {% endif %}Sub Categoria</div>
    <div class="dropdown-divisor"></div>
    <div class="row">
        <div class="col-5">
            <div class="input-group">
                {% comment %} <input type="text" name="categoria" maxlength="100" class="form-control" required id="categoria" placeholder="Categoria" value="{% if obj %} {{ obj.categoria }} {% endif %}"> {% endcomment %}
                {{ form.categoria }}
            </div>
        </div>
        <p></p>
        <p></p>
        <div class="col-5">
            <div class="input-group">
                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{ obj.descripcion }} {% endif %}">
            </div>
        </div>
        <p></p>
        <p></p>
        <div class="col">
            <div class="form-group">
                <label for="id_estado">Estado</label>
                <input type="checkbox" id="id_estado" name="estado" value="" {% if obj.estado %} checked {% endif %}>
            </div>
        </div>
    </div>
    <p></p>
    <p></p>
    <div class="dropdown-divisor">
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span> Cancelar</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Listado de Sub Categorias</h1>
<p></p>
<div>
    <a class="btn btn-primary" href="{% url 'inv:subcategoria_new' %}" role="button"><i class="fa fa-plus-square"></i> Nueva</a>
</div>
<p></p>
{% if not obj %}
<div class="alert alert-info">No hay Sub Categorias</div>
{% else %}
<table class='table table-striped table-hover'>
    <thead>
        <tr>
            <td>Categoria</td>
            <td>Id</td>
            <td>Descripcion</td>
            <td>Estado</td>
            <td>F. Creado</td>
            <td>F. Modif</td>
            <td class="all">Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% if obj %} {% for item in obj %}
        <tr>
            <td>{{item.categoria}}.</td>
            <td>{{item.id}}.</td>
            <td>{{item.descripcion}}.</td>
            <td>{{item.estado|yesno:"Activo, Inactivo"}}</td>
            <td>{{item.fc|date:'d/m/y H:i:s'}}</td>
            <td>{{item.fm|date:'d/m/y H:i:s'}}</td>

            <td>
                <a class="btn btn-warning btn-circle" href="{% url 'inv:subcategoria_edit' item.id %}" role="button"><i class="far fa-edit"></i></a>

                {% comment %} <a class="btn btn-danger btn-circle" href="{% url 'inv:subcategoria_del' item.id %}" role="button"><i class="far fa-trash-alt"></i></a> {% endcomment %}
            </td>
        </tr>
        {% endfor %} {% else %}
        <h1>No hay registros de empleados</h1>
        {% endif %}
        <tbody>
</table>
{% endif %}

<br>
<div class="pagination">
    <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Primero</a>
            <a href="?page={{ page_obj.previous_page_number}}">Previo</a>
            {% endif %}
            <span class="current">
                Página {{page_obj.number}} de {{page_obj.paginator.num_pages}}.
            </span> {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number}}">Siguiente</a>
    <a href="?page={{ page_obj.paginator.num_pages}}">Último &raquo;</a> {% endif %}
    </span>
</div>

{% endblock %}

{% block js_page %}
<script>
    //Llamamos al plugin del datatable
    $(document).ready(function(){
        $('.table')DataTable();
    });
</script>
{% endblock %}